### ISSUE TITLE
product_types should be an array of Strings

### ISSUE THREAD

**Issue by PEM--** [EasySize/EasySize-integration#1]
In https://github.com/EasySize/EasySize-integration/wiki/EasySize-RESTful-API-integration#check-product, the `product_types` is specified as a `String` but the example depicts an array of Strings and the description is mentioning a JSON Array.

**Comment by ByEmke** [comment]
Hello @PEM-- , it should be a JSON Array of strings, an example in javascript would look like this:

```javascript
product_types: JSON.stringify(['Menwear', 'Jeans']),
...
```

We will try to clarify this description a bit, thanks for the feedback!
