### ISSUE TITLE
Secured API endpoint?

### ISSUE THREAD

**Issue by PEM--** [EasySize/EasySize-integration#3]
In https://github.com/EasySize/EasySize-integration/wiki/EasySize-RESTful-API-integration#api, the main API endpoint is a raw HTTP v1.1 URL without TLS `http://api.easysize.me/v1/`.

Do you provide a secured one?

**Comment by ByEmke** [comment]
Hi @PEM-- , yes, we do provide a secure API, and we would actually suggest sticking with the secured one. I will go through the documentation and update the URLs. Thanks for your feedback!
